### PR TITLE
refactor(Commitizen): added commitizen

### PR DESCRIPTION
**Pull request by stoffern**
@nodkz 
added commitizen
From now on use:
```
git add .
git cz (replace for git commit, using git cz will give you a menu to choose from :) )
git push origin ...
```

### CODE REVIEW

**Comment by nodkz** [comment]
Give me some time for reading about `commitizen`.
After that I'll accept PR.

PS. If you found a great article about this thing (non-official), please share a link.

**Comment by stoffern** [comment]
https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-writing-conventional-commits-with-commitizen

i have allready done the installation for you so you just do:
```
npm i
git add .
git cz
git push..
```

**Comment by stoffern** [comment]
`git cz` = `npm run commit` in the video

**Comment by nodkz** [comment]
Thanks for the motivation to view all Kent C. Dodds' videos. It's very useful.

**Comment by stoffern** [comment]
now you just need to add semantic-release :smile: 

```
npm i -g semantic-release-cli
cd your-module
semantic-release-cli setup
```

**Comment by nodkz** [comment]
With `graphql-compose` do it later.
Firstly play with sem-releases on https://github.com/nodkz/graphql-compose-connection and other plugins.

**Comment by stoffern** [comment]
@nodkz awesome that you implemented semantic-release to! :clap: :tada: 
It makes it alot easier :wink:

**Pull request merged**
