### PR TITLE
docs(quick start guide readme): update link for mutations

### PR DESCRIPTION
**Pull request by sensone**
typo

### CODE REVIEW

**Comment by nodkz** [comment]
Evgeni thanks a lot.

**Comment by stoffern** [comment]
thanks for PR, i forgot to write 😉

**Comment by sensone** [comment]
@nodkz, @stoffern your tool looks great, and I'm happy help you.
I try to understand how does it works now, but may be in the future I'll be more useful ))

**Comment by nodkz** [comment]
@sensone Will be cool if you keep somewhere questions (weird complex parts) due to your understanding process (can do it in Russian) and send me via email. It helps to me in future improve docs.

For now too much work before vacation, I just finished [graphql-compose-elasticsearch](https://github.com/nodkz/graphql-compose-elasticsearch) and have only 2 days for integrating it into our internal app.

**Comment by sensone** [comment]
@nodkz, I have too much work too now and I think I'll do it after 2-3 weeks may be more. It depends How many time I will have for writing code with graphal-compose.
For me most of questions are:
- Ok, I have server with graphql api and I would like to create react-relay app. How I should start it? 
- What I will be do with mutations (It looks terrible for me now(about relay))
For me most useful were graphql-compose-examples, and together with documentation I understand how it works. I haven't seen yet how I could be write unit tests, but this question for future

Thank you

**Pull request merged**
